Cloud Sign Up Landing Page
gravitational/next pull request #263
Opened 2021-05-24 13:53 UTC by Saionaro

2021-05-27 15:35 UTC, klizhentas requested changes

2021-05-27 15:35 UTC, klizhentas commented on pages/cloud-trial/index.mdx
> +  subtitle="Access Plan"
Access Plane

2021-05-27 16:46 UTC, Saionaro commented on pages/cloud-trial/index.mdx
> +  subtitle="Access Plan"
```suggestion
  subtitle="Access Plane"
```

2021-05-27 16:47 UTC, Saionaro commented on pages/enterprise-trial/index.mdx
> +  subtitle="Access Plan"
```suggestion
  subtitle="Access Plane"
```

2021-05-28 09:28 UTC, Saionaro commented on components/Video/Video.tsx
> +        // maxWidth="100%"
```suggestion
```

2021-05-28 09:31 UTC, Saionaro commented on pages/cloud-trial/index.mdx
> +  Button,
```suggestion
```

2021-05-28 09:32 UTC, Saionaro commented on pages/enterprise-trial/index.mdx
> +  Button,
```suggestion
```

2021-05-31 16:05 UTC, merged