Access plane pages
gravitational/next pull request #320
Opened 2021-06-17 21:14 UTC by iAdramelk

Two new pages:

- `/access-request/`.
- `/mfa/`.

Todo:

- [ ] Update code blocks in tabs.
- [ ] Fix link to video on mfa page.
- [ ] Change URLs.
- [ ] Add headers and description.
- [ ] Animate code block in mfa header.
- [ ] Animate code block on access request page.

2021-06-17 22:01 UTC, klizhentas reviewed
@iAdramelk please update the code snippets

2021-06-17 23:26 UTC, klizhentas requested changes
Let's address Ev's comments:

My comments by looking at staging:

Remove "Core features" subtitle. Those things are not "core features"
Remove "Approve access" subtitle. It makes no sense.
Swap the two blocks: "Move away from root accounts" block needs to be on top, with "Works with existing tools" a the bottom.

2021-06-17 23:32 UTC, klizhentas commented on pages/access-request/index.mdx
> +      $ tsh request create --roles=dba \
```
$ tsh request create --roles=dba \
   --reviewers=alice@example.com,ivan@example.com --reason="ticket #123"

# Alice
$ tsh request review --approve --reason="proceed with caution" 

# Ivan
$ tsh request review --approve --reason="granted." 


```

2021-06-17 23:32 UTC, klizhentas commented on pages/access-request/index.mdx
> +      $ tsh request create --roles=dba \
```bash
$ tsh request create --roles=dba \
   --reviewers=alice@example.com,ivan@example.com --reason="ticket #123"

# Alice
$ tsh request list

# Output
ID                                   User             Roles   Created (UTC)       Status
------------------------------------ ---------------  ------- ------------------- ------- 
9c721e54-b049-4ef8-a7f6-c777aa066764 bob@example.com  dba 03 Apr 21 03:58 UTC PENDING

$ tsh request review --approve --reason="proceed with caution" 9c721e54-b049-4ef8-a7f6-c777aa066764

```

2021-06-17 23:32 UTC, klizhentas commented on pages/access-request/index.mdx
> +<SectionSteps title="Access Requests Flow" description={<>To learn more about Access Workflows, take a look at <Link href="/docs/" scheme="site">Teleport Documentation</Link>.</>}>
To learn more about access requests, take a look at ...

2021-06-18 19:34 UTC, klizhentas commented
@iadramelk let’s move them under /features/multi-factor-auth and /features/access-requests tomorrow and you can merge. We can finish animation and other tweaks later.

2021-06-19 04:01 UTC, iAdramelk commented
@klizhentas renamed and merged.

2021-06-19 04:01 UTC, merged