Add fallback local url to marketo
gravitational/next pull request #329
Opened 2021-06-24 11:33 UTC by iAdramelk

Fix #327

Marketo didn't work in Firefox and Safari because of tracking cookie protection. This PR adds optional proxying for the Marketo request view goteleport.com domain if the original script is blocked.

To make it work we need to add following rewrites to nginx:

- `^js/forms2/(.*)` -> `http://app-ab44.marketo.com/js/forms2/$1`
- `^form/getForm` -> `http://app-ab44.marketo.com/form/getForm`
- `^form/getKnownLead` -> `http://app-ab44.marketo.com/form/getKnownLead`
- `^index.php/leadCapture/save2` -> `http://app-ab44.marketo.com/index.php/leadCapture/save2`

CC @klizhentas ^

2021-06-24 11:38 UTC, iAdramelk commented
For details see https://blog.darwinapps.com/solution-to-embedded-marketo-forms-not-showing-up-in-firefox-c3780e6f8609

2021-06-24 17:01 UTC, alex-kovoy approved these changes
with comments

2021-06-24 17:01 UTC, alex-kovoy commented on utils/marketo.ts
> +  }, [url, formId, callback]);
I would remove the `callback` from the dep list as changed callback is something that regularly happens. So it should not trigger multiple `window.MktoForms2.loadForm` in this case.

If you want to guarantee that this callback is always captured by that component, you can do this:

```ts
const ref = useRef(callback);

useEffect(() => {
    if (!url) {
      loadScript(NEXT_PUBLIC_MARKTO_BASE_URL)
        .catch(() => loadScript(NEXT_PUBLIC_HOST))
        .then(setUrl)
        .catch((e) => console.error(e));

      return;
    }

    const cb = () => ref.current();

    window.MktoForms2.loadForm(
      url,
      NEXT_PUBLIC_MARKTO_MUNCHKIN_ID,
      formId,
      cb);
}, [url, formId, ref]);      
```

2021-07-06 18:10 UTC, klizhentas requested changes
@iAdramelk this solution seems fragile - the moment Marketo switches the API, it would break and we would never know. What are the alternatives?

2021-07-07 05:26 UTC, iAdramelk commented
> @iAdramelk this solution seems fragile - the moment Marketo switches the API, it would break and we would never know. What are the alternatives?

@klizhentas we may create separate domain/subdomain and redirect 100% calls from it to Marketo (or use cloudfire subdomain domain for this). This way even if Marketo API changes in the future, calls will still be made.

2021-07-08 21:21 UTC, klizhentas commented
@iAdramelk I chatted to @alexwolfe and @kontsevoy. We want to switch our existing forms to Next engine and have a sync with marketo on the backend. Alex will let you know where is this on the priority list. Form requirements from me:

* Recaptcha just like on cloud form
* Marketo call on the backend with alert if it failed (and ideally retry)
* Consult with @alex-kovoy regarding security
* 
Please factor this out in a separate issue, and ask @alexwolfe about priority of this. You would need a list of forms from Alex with a spec and designs.

2021-09-08 16:19 UTC, closed without merging