Cole/newsletter
gravitational/next pull request #345
Opened 2021-07-06 22:48 UTC by C-STYR

2021-07-08 17:32 UTC, iAdramelk requested changes

2021-07-08 17:32 UTC, iAdramelk commented on components/Newsletter/Card.tsx
> +    width: [343, 944],
Same as above.

2021-07-08 17:32 UTC, iAdramelk commented on components/Newsletter/Card.tsx
> +    marginBottom: ["56px", "32px"],
```suggestion
    marginBottom: [8, 5],
```

2021-07-08 17:32 UTC, iAdramelk commented on components/Newsletter/EmailCTA.tsx
> +    height: [298, 392],
Same 3 comments as in 2 previous blocks. Also `white for` color in case we decide to change it in theme.ts.

2021-07-08 17:32 UTC, iAdramelk commented on components/Newsletter/NewsletterEmailSubscribe.tsx
> +        minWidth={["307px", "304px"]}
You can make them take full width by setting `alignItems: stretch` instead of `center` in the parent div.

2021-07-08 17:32 UTC, iAdramelk commented on components/Newsletter/NewsletterEmailSubscribe.tsx
> +      fontSize: ["text-md", "text-xl !important"],
Will the first one work without `!important`? (Also not sure that `text-xl` works together with `!imporant`, I thought it should be direct math to value).

2021-07-08 17:32 UTC, iAdramelk commented on pages/newsletter/index.tsx
> +        minHeight="100vh"
You can move `backgroundImage` and `minHeight` to `FlexBG`. Also to make it easier to understand component roles, I prefer to start purely styled component component with `Styled` prefix. E. g. `StyledFlexBG`. This way it is easier to understand if component have some logic in it of is just pure visual one.

2021-07-08 17:32 UTC, iAdramelk commented on pages/newsletter/index.tsx
> +        <Box m={["62px 0px 32px", "48px 0px 32px"]}>
I'd round `62` to `64` here and then replace values with the ones form the `theme.ts`.

2021-07-08 17:32 UTC, iAdramelk commented on pages/newsletter/index.tsx
> +          <Box as="h1" m={"0 0 0 0"}>
```suggestion
          <Box as="h1" m={0}>
```

2021-07-08 17:32 UTC, iAdramelk commented on pages/newsletter/index.tsx
> +                width={["120px", null]}
```suggestion
                height={["24px", "auto"]}
                width={["120px", "auto"]}
```

2021-07-08 17:32 UTC, iAdramelk commented on pages/newsletter/index.tsx
> +            <a href="/">
Please use NextLink here. RIght now `/` on old engine, but after we migrate it, we want it to be automatically routed.

2021-07-08 17:32 UTC, iAdramelk commented on pages/newsletter/index.tsx
> +            <a href="/">
Also every link should have `hover`, `active` and `focused` styles. In image case you can use `opacity` for that.

Alternatively you can replace white color in the svg file with `current` color, load svg as `{ reactComponent }` and change logo color on hover by adding `color` attribute. Check icons svg files and component for example.

2021-07-08 17:32 UTC, iAdramelk commented on pages/newsletter/index.tsx
> +                  width={"100%"}
```suggestion
                  width="100%"
```

2021-07-08 17:32 UTC, iAdramelk commented on pages/newsletter/index.tsx
> +                fontWeight={"bold"}
```suggestion
                fontWeight="bold"
```

2021-07-08 17:32 UTC, iAdramelk commented on pages/newsletter/index.tsx
> +                p={["6px 16px 10px 18px", "12px 56px 14px 56px"]}
I think it's ok to change `6px` to `8px` here. And `18px` and `14px` to `16px`. It such cases its more often mistake in the avocode that intention. Leave `12px` through. It's used in different places and is not in the styled system mostly because adding it will break order.

2021-07-08 17:32 UTC, iAdramelk commented on pages/newsletter/index.tsx
> +                fontSize={["15px", "text-lg"]}
Change it to `text-md` or `text-lg`. Having only one place on site with `15px` is not viry consistent. If you are not sure which is better, ask Alex or Anya.

2021-07-08 17:32 UTC, iAdramelk commented on pages/newsletter/index.tsx
> +                px={["18px", 8]}
```suggestion
                lineHeight={["20px", "md"]}
                fontWeight="regular"
                width="100%"
                px={[3, 8]}
```

2021-07-08 17:32 UTC, iAdramelk commented on pages/newsletter/index.tsx
> +              height={[298, 392]}
I'd try to do this place and ones below without absolute values to width and height.

2021-07-08 17:32 UTC, iAdramelk commented on pages/newsletter/index.tsx
> +                <Box fontSize={["17px", "18px"]} width="100%" pb={[null, 3]}>
```suggestion
                <Box fontSize="text-xl" width="100%" pb={[0, 3]}>
```

`17px` is not in our theme and too close to `18px` anyway. If it not fit mobile version, reduce it to `16px`.

2021-07-08 17:32 UTC, iAdramelk commented on pages/newsletter/index.tsx
> +            <a href="/tos/">
Please use `NextLink` here and below. You probably want to combine link and `TermsText` together and add `hover/active/focus`.

2021-07-08 17:32 UTC, iAdramelk commented on pages/newsletter/index.tsx
> +const FlexBG = styled(Flex)<StyledSystemProps>(
If you extends `Flex` or `Box`,you don't need to add `all` or `StyledSystemProps`, they will be inherited from the parent automatically.

2021-07-08 17:32 UTC, iAdramelk commented on pages/newsletter/index.tsx
> +const Copyright = styled("div")<StyledSystemProps>(
You may omit `StyledSystemProps`, because it does not accept style system props.

2021-07-08 17:32 UTC, iAdramelk commented on pages/newsletter/index.tsx
> +    width: "459px",
You don't need width here.

2021-07-08 17:32 UTC, iAdramelk commented on pages/newsletter/index.tsx
> +    height: "14px",
Probably don't need height here too. You can just make top margin from `TermsText` a little smaller.

2021-07-08 17:32 UTC, iAdramelk commented on pages/newsletter/index.tsx
> +    margin: "12px 5px 60px 5px",
Try values closer to the ones in theme. In most cases if margin/padding between items are slightly different from module (8px) * some value. It's probably unintentional and you need to try module value first to check how it looks.

2021-07-08 17:50 UTC, C-STYR commented on pages/newsletter/index.tsx
> +        minHeight="100vh"
FlexBG is reused elsewhere (inside AccessPlane) with different image, so `backgroundImage`  and `minHeight` should stay inline I think.

2021-07-08 19:29 UTC, C-STYR commented on pages/newsletter/index.tsx
> +            <a href="/">
`hover` etc. resolved, also used `Link` from 'components/Link.  If the `/` href is not the correct one when using `Link`, please advise re the correct href.

2021-07-08 19:54 UTC, C-STYR commented on components/Newsletter/NewsletterEmailSubscribe.tsx
> +        minWidth={["307px", "304px"]}
In theory, yes, but this breaks the marketo proprietary styling and requires much more code to fix.

2021-07-08 23:20 UTC, C-STYR commented on pages/newsletter/index.tsx
> +        minHeight="100vh"
Also, renamed it `StyledBackground`

2021-07-08 23:44 UTC, alexwolfe commented
Great work @C-STYR thanks for reviewing this @iAdramelk 

Can we push this out ASAP? Marketing needs this one live. I looked at it and it looks ready to go. If you two have some code optimizations perhaps we can put that in a future branch. Thanks!

2021-07-09 08:15 UTC, iAdramelk approved these changes
Please fix links and you can release. We can fix nitpicks after releasing it.

2021-07-09 08:15 UTC, iAdramelk commented on pages/newsletter/index.tsx
> +    width: [343, 944],
Nit: You probably don't need height here (especially on mobile, it may break on some mobile resolutions because of different).

You need width on desktop, but on mobile to make it 100% or it will break on some resolutions.

2021-07-09 08:15 UTC, iAdramelk commented on pages/newsletter/index.tsx
> +const Card = styled(Flex)(
Nit: Can you name it `StyledCard`?

2021-07-09 08:15 UTC, iAdramelk commented on pages/newsletter/index.tsx
> +const AccessPlane = styled(Flex)(
Nit: Can you name it `StyledAccessPlane`?

2021-07-09 08:15 UTC, iAdramelk commented on pages/newsletter/index.tsx
> +const TermsText = styled("div")(
Nit: Can you name it `StyledTermsText`? (of `StyledTermsLink` if you combine it with link).

2021-07-09 08:15 UTC, iAdramelk commented on pages/newsletter/index.tsx
> +const Copyright = styled("div")(
Nit: `StyledCopyright`

2021-07-09 08:15 UTC, iAdramelk commented on pages/newsletter/index.tsx
> +const EmailCTA = styled("div")<StyledSystemProps>(
Nit `StyledEmailCTA`.

2021-07-09 08:15 UTC, iAdramelk commented on pages/newsletter/index.tsx
> +                lineHeight={["20px", "24px"]}
```suggestion
                lineHeight={["20px", "md"]}
```

2021-07-09 08:15 UTC, iAdramelk commented on pages/newsletter/index.tsx
> +                lineHeight={["22px", "24px"]}
```suggestion
                lineHeight={["22px", "md"]}
```

Nit: Probably ok just to make both `md, but need to check`.

2021-07-09 08:15 UTC, iAdramelk commented on components/Newsletter/NewsletterEmailSubscribe.tsx
> +      flexDirection={["column", "row"]}
```suggestion
      alignItems="stretch"
      flexDirection="column"
```

Nit: Need to test in actual browser, but this way you should be able to remove `minWidth` from the child element. Also you can remove child `Box` entirely and move all its props to this `Flex`.

2021-07-09 16:24 UTC, C-STYR commented on pages/newsletter/index.tsx
> +                  fontWeight={"bold"}
header-4 is much too small, went with 3

2021-07-09 16:36 UTC, iAdramelk commented on pages/newsletter/index.tsx
> +            <a href="/">
`/` should work.

2021-07-09 17:54 UTC, C-STYR commented on components/Newsletter/NewsletterEmailSubscribe.tsx
> +      flexDirection={["column", "row"]}
Removing minWidth doesn't work - we'll have to revisit this another time.

2021-07-09 18:23 UTC, C-STYR commented on components/Newsletter/NewsletterEmailSubscribe.tsx
> +      flexDirection={["column", "row"]}
Removing minWidth breaks at various resolutions.  Will need to revisit this later.

2021-07-09 18:33 UTC, C-STYR commented on pages/newsletter/index.tsx
> +    width: [343, 944],
removed height, however, width must be retained as we are shooting for a static mobile card

2021-07-09 19:49 UTC, alexwolfe commented
Thanks for all the work guys. I'm merging and deploying today. Please include any other updates in another branch/pr.

2021-07-09 19:50 UTC, merged