Cole/features
gravitational/next pull request #352
Opened 2021-07-15 19:52 UTC by C-STYR

fixes #348

2021-07-19 11:54 UTC, iAdramelk requested changes
Let's rename images to follow the same naming convention. Right now we have: `How-it-works.png`, `audit-log.png ` and `enterpriseBG.png` at the same time.

I use `lower-case-kebab-case` then possible.

2021-07-19 11:54 UTC, iAdramelk commented on pages/features/index.mdx
> +  <Flex flexDirection="row" pl={[3, 4, 11]} pt={[4, 7, 9]} pb={[4, 6]}>
We use reusable components as much as we want. So to make tiles block reusable we should probably create separate component for tiles' group with `icon`, `title` and `children` fields. It will be also easier to use on this page, because it is already repeated twice.

2021-07-19 11:54 UTC, iAdramelk commented on pages/features/index.mdx
> +      <FeatureTile
This component is used for features on this page, but it can be used for something also on the other page, so I'd rename to something more neutral.

 Also instead of exporting it separately, we better export is as a part of the parent component and in case of `SectionTabs`.

2021-07-19 11:54 UTC, iAdramelk commented on pages/features/index.mdx
> +  <Flex px={[3, 3, 10]} pb={6}>
Right now features take 100% of the screen, but we probably want to limit maximum with of the contetn, or it will become unreadable on the larger screens. You can use `layout/Cetrator` component for this it will limit max width and center content for sections. You can check examples of its usage in `Section*` component.

2021-07-19 11:54 UTC, iAdramelk commented on pages/features/index.mdx
> +    <Icon name="apartment" size="lg" fill="#512FC9" />
Let's try to use `color` here. If it still doesn't work after moving to `tsx` component, please let me know and we will debug it together.

2021-07-19 11:54 UTC, iAdramelk commented on pages/features/index.mdx
> +  <Flex flexDirection="column" alignItems="flex-end" px={[4, 5, 11]} pt={6}>
We better move it to separate component too. Also we probably should discuss with Alex Wolfe hot to make it more universal so we can use it not only on this page, but also on the others.

2021-07-19 11:54 UTC, iAdramelk commented on pages/features/index.mdx
> +      <h1 color="darkest" fontSize="header-1" >How Teleport Works</h1>
Page can have only 1 `h1` header. So let's switch it to `h2`. Also `styled-system` will not work with `<h1>` directly, to make it works we need to use `<Box as="h2"></Box>`.

2021-07-19 11:54 UTC, iAdramelk commented on pages/features/index.mdx
> +        src="./assets/How-it-works.png"
Image is blurry on the actual site now.  As for the section itself, lets try to use `<Centrator>` too. We probably want to limit it's max width with absolute value that is equal to the real image dimensions and center it.

2021-07-19 11:54 UTC, iAdramelk commented on pages/features/index.mdx
> +import FeatureTileDisplay from "components/Tile/FeatureTileDisplay";
to make it easier to use we want to reduce number of import sources. In the perfect world we want to import all components from `components`.

2021-07-19 11:54 UTC, iAdramelk commented on components/Tile/FeatureTileDisplay.tsx
> +    <Flex
We probably want to use `import { Centrator } from "components/layout"` here to limit max width of the component. And also move section header here too (see comment in the `page/features` for details).

Also we probably want to move wrapper itself to it's own folder instead of `Tile`.

2021-07-19 11:54 UTC, iAdramelk commented on components/Tile/FeatureTile.tsx
> +const StyledButton = styled(Button)({
Lets discuss with Alex how often we want to use this styles. We want consistent button styles across the site. So should either leave them as they are in `Button` already, or add new variation to the `Button`component itself.

2021-07-19 11:54 UTC, iAdramelk commented on components/Tile/FeatureTile.tsx
> +    maxHeight: "500px",
Why do we need fixed `minWidth` and fixed `minHeight` here? Technically we only want to have some fixed number of elements in the line and for them to have the same height.

We can do first by changing  `calc((100% - 80px) / 4)` this line to something like `calc((100% - 60px) / 3)` (60px should be replaced width the sum of gsaps between elements).

Second should automatically work with `alignItems: stretch`.

2021-07-19 11:54 UTC, iAdramelk commented on components/Tile/FeatureTile.tsx
> +        <Box fontSize="13px" lineHeight="md" color="gray" pb={3}>
Let's replace it with the value form the `theme.ts`, we don't want to add rendom sizes here. And let's discuss it with Alex if needed.

2021-07-19 11:54 UTC, iAdramelk commented on components/Tile/FeatureTile.tsx
> +      <Flex flexDirection="column-reverse" px={4} pb={4} height="100%">
```suggestion
      <Flex flexDirection="column-reverse" px={4} pb={4} flexGrow={1}>
```

2021-07-19 11:54 UTC, iAdramelk commented on components/Tile/FeatureTile.tsx
> +        <NextImage src={src} alt={`${title}`} height={193} width={282} />
Are we sure that all images we use in this component will have these sizes?

2021-07-19 11:54 UTC, iAdramelk commented on components/Tile/FeatureTile.tsx
> +  const backgroundImage = feature === "enterprise" ? enterpriseBG : coreBG;
Let's make this prop name more neutral. We may want to use this component not only for the features.

2021-07-19 11:54 UTC, iAdramelk commented on components/Section/Section.tsx
> +        backgroundColor: "#f6f8f9",
```suggestion
        backgroundColor: "page-bg",
```

2021-07-19 11:54 UTC, iAdramelk commented on components/Section/Section.tsx
> +        backgroundColor: "#ffffff",
We don't need this one. It's a default value (see below).

2021-07-19 11:54 UTC, iAdramelk commented on components/Icon/svg/circleCheck.svg
> +<path d="M9.5 20c-2.538 0-4.923-0.988-6.718-2.782s-2.782-4.18-2.782-6.717c0-2.538 0.988-4.923 2.782-6.718s4.18-2.783 6.718-2.783c2.538 0 4.923 0.988 6.718 2.783s2.782 4.18 2.782 6.718-0.988 4.923-2.7
Let's change both `fill` values to `currentColor` from `#000000`.

2021-07-19 11:54 UTC, iAdramelk commented on components/Icon/Icon.tsx
> +      <IconSVG width="100%" height="100%" display="block" fill={fill} />
We don't need `fill` here if we use `currentColor` in the icons.

2021-07-19 11:54 UTC, iAdramelk commented on components/Header/Header.tsx
> +      return <></>;
You can return `''` or `false` or `undefuned` here. it will render correctly.

2021-07-19 14:05 UTC, alex-kovoy commented on components/Header/Header.tsx
> +  }, [isNavigationVisible]);
This is not a good case for using `useCallback`, a simple function would do.

```js
 const toggleNavigaton = () => {
    setIsNavigationVisible(!isNavigationVisible);
    blockBodyScroll(isNavigationVisible);
};
```  

Here is a nice article on the subject.
https://dmitripavlutin.com/dont-overuse-react-usecallback/

2021-07-19 17:42 UTC, C-STYR commented on components/Header/Header.tsx
> +  }, [isNavigationVisible]);
@alex-kovoy  thanks for the review--just to let you know, the code you have commented on exists within this PR only as an artefact of merge conflict resolution with PR #350; I am not in fact the author of the useCallback code block.

Please see here: [PR #350 ](https://github.com/gravitational/next/pull/350/files)

I will however enjoy the article you posted, thanks.

2021-07-19 18:55 UTC, C-STYR commented on pages/features/index.mdx
> +        src="./assets/How-it-works.png"
Alex wanted the image aligned left, not centered, but I'll discuss with him.

2021-07-20 18:52 UTC, C-STYR commented on components/Section/Section.tsx
> +        backgroundColor: "#ffffff",
The default value also has a wave image overlay, which we would then need to be removed on a case-by-case basis, unless I'm misunderstanding?

2021-07-20 18:54 UTC, iAdramelk commented on components/Section/Section.tsx
> +        backgroundColor: "#ffffff",
You are right, I missed them, because they were not shown in PR>

2021-07-20 18:55 UTC, C-STYR commented on components/Header/Header.tsx
> +      return <></>;
This seems stylistic...is there a performance or other benefit, or just conventional?

2021-07-20 18:58 UTC, iAdramelk commented on components/Header/Header.tsx
> +      return <></>;
It's more conventional, `<></>` will add additional import and function call, but its performance impact will probably be negligible. You can disregard it if you want.

2021-07-20 23:40 UTC, C-STYR commented on components/Tile/FeatureTile.tsx
> +        <Box fontSize="13px" lineHeight="md" color="gray" pb={3}>
Per Alex, it's going to stay at 13px and we're going to add it to theme.ts

2021-07-20 23:45 UTC, C-STYR commented on components/Tile/FeatureTile.tsx
> +      <Flex flexDirection="column-reverse" px={4} pb={4} height="100%">
Interesting, you'll have to explain your preference to me.  I would have thought the two were functionally equivalent.

2021-07-21 16:07 UTC, iAdramelk commented on components/Tile/FeatureTile.tsx
> +      <Flex flexDirection="column-reverse" px={4} pb={4} height="100%">
`height: 100%` is calculated form something. Usually form the height of the parent container. It will work in a lot of cases, but if we have other children with some height or if their height is calculated in % too it may not. `flexGrow: 1` in this case is sayng that container should take all "free" space in the container (its acutually more comlpex because multiple elements can have `flexGrow` and `flegGrow` value may be more that `1`, but in this case it is like this).

2021-07-21 23:51 UTC, merged