Video bar
gravitational/next pull request #367
Opened 2021-08-02 12:35 UTC by Alqanar

added video bar component

2021-08-02 14:06 UTC, iAdramelk requested changes

2021-08-02 14:06 UTC, iAdramelk commented on components/VideoBar/VideoBar.tsx
> +  videoDurationSec?: number;
```suggestion
  thumbnail: string;
  href: string;
  title: string;
  duration?: number;
```

We don't need `video` prefix here, because the is only video here. Also `title` and `href` and the names that we use for such props in other components, so I renamed them, for consistency.

2021-08-02 14:06 UTC, iAdramelk commented on components/VideoBar/VideoBar.tsx
> +    <StyledVideoBar
Let's by default use standard elements like `Box` and `Flex` and only use styled components if we have nested styles or variations.

This way we can read code in a flow and wouldn't need to scroll back and forth before style definition and component body.

2021-08-02 14:07 UTC, iAdramelk commented
Please check mobile version, button is broken.

<img width="354" alt="image" src="https://user-images.githubusercontent.com/451207/127874545-64e670cf-688f-4569-999a-36871e24a972.png">

2021-08-02 17:33 UTC, Alqanar commented on components/MDX/MDX.tsx
> +  VideoBar,
Yep, I understand, I added it for debug purposes only. Removed

2021-08-02 17:33 UTC, Alqanar commented on components/VideoBar/VideoBar.stories.tsx
> +  </MDX>
Removed

2021-08-02 17:34 UTC, Alqanar commented on components/VideoBar/VideoBar.tsx
> +  console.log(previewSrc);
My bad... Removed

2021-08-02 17:39 UTC, Alqanar commented on components/VideoBar/VideoBar.tsx
> +  videoDurationSec?: number;
fixed

2021-08-02 18:07 UTC, Alqanar commented on components/VideoBar/VideoBar.tsx
> +    <StyledVideoBar
Yes, sure. But I follow the rule - if properties are a lot, I will take them out in styled components. Now I made a mistake in one place, and I fixed it

2021-08-02 18:23 UTC, Alqanar commented
> Please check mobile version, button is broken.
> 
> <img alt="image" width="354" src="https://user-images.githubusercontent.com/451207/127874545-64e670cf-688f-4569-999a-36871e24a972.png">


Fixed. New version:

<img width="330" alt="Screenshot 2021-08-03 at 01 20 41" src="https://user-images.githubusercontent.com/41822696/127906546-2accdb75-6d05-43ed-a6d5-048d2fb0c14a.png">

2021-08-03 08:24 UTC, iAdramelk approved these changes
Approved with nitpicks.

2021-08-03 08:24 UTC, iAdramelk commented on components/VideoBar/VideoBar.stories.tsx
> +import Img from "./assets/video-bar.png";
Lets rename folder to `fixture`. `assets` - images that are part of components, `fixtures` – images for tests and storybook.

2021-08-03 08:24 UTC, iAdramelk commented on components/VideoBar/VideoBar.tsx
> +        <StyledIcon name="play" size="md" opacity={0.57} />
IF we want to use `styled` component here, let's move size and opacity there too, to have everything in the same place.

2021-08-03 08:51 UTC, Alqanar commented on components/VideoBar/VideoBar.tsx
> +        <StyledIcon name="play" size="md" opacity={0.57} />
I moved opacity in the styled components, but "size" is the parameter of the component Icon.

2021-08-03 11:45 UTC, merged