EasyStart Component
gravitational/next pull request #373
Opened 2021-08-06 19:11 UTC by C-STYR

<img width="1226" alt="Screen Shot 2021-08-06 at 11 06 21 AM" src="https://user-images.githubusercontent.com/73362670/128560171-0d7f53ed-7974-4d7c-8b3d-ec1762e42f09.png">

2021-08-09 12:06 UTC, iAdramelk requested changes

2021-08-09 12:06 UTC, iAdramelk commented on components/EasyStart/EasyStart.tsx
> +                  The <StyledSpan>tsh</StyledSpan> client allows users to login
Two comments here:

1. We should use `code` here, instead of `span`.
2. We have different styles that we use for code blocks on other pages, so we probably should unify them. See STEP 1 on this page for example https://goteleport.com/features/access-requests/ .

2021-08-09 12:06 UTC, iAdramelk commented on components/EasyStart/EasyStart.tsx
> +            <Flex width={["auto", "50%"]}>
If we leave this block inside `{children}`, we can render it using code block ``` syntax, it will automatically add syntax highlight on render. See https://github.com/gravitational/next/blame/main/pages/features/access-requests/index.mdx#L55-L70 for an example.

If we want to hardcode it, we should use for `hl.js` classnames and styles from the current `code` component, so if will not be broken in the case we change code theme in the future. See current classes here https://github.com/gravitational/next/blob/main/components/Code/Code.tsx

2021-08-10 16:51 UTC, C-STYR commented on components/EasyStart/EasyStart.tsx
> +            <Flex width={["auto", "50%"]}>
Spoke to Alex, we're going to nix the generic black box and move to Terminal component in .mdx file.

2021-08-10 19:33 UTC, C-STYR commented on components/EasyStart/EasyStart.tsx
> +                  The <StyledSpan>tsh</StyledSpan> client allows users to login
done

2021-08-10 19:33 UTC, C-STYR commented on components/EasyStart/EasyStart.tsx
> +    <Flex background={`url(${wavelight}) 0 0 no-repeat`}>
done

2021-08-10 19:36 UTC, C-STYR commented on components/EasyStart/EasyStart.tsx
> +              Easy to get started
Per Alex, we are going to keep these props hard-coded.  This banner will exist on all four products pages as well as the homepage and in order to enforce consistency props will not be modifiable in .mdx.

2021-08-10 20:28 UTC, merged