added sitemap for docsearch
gravitational/next pull request #418
Opened 2021-09-08 14:41 UTC by Alqanar

2021-09-09 13:06 UTC, iAdramelk requested changes

2021-09-09 13:06 UTC, iAdramelk commented on utils/paths.ts
> +    path: resolve("public", "sitemap.xml"),
Cole in #420 already renamed it (we need it named differently from `sitemap.xml` to merge hugo's one and ours), so let's leave this one outside the scope of this PR.

2021-09-09 13:06 UTC, iAdramelk commented on utils/paths.ts
> +  const sitePages = getNonDocsPaths().map((loc) => ({ loc }));
We do not need site pages for the Algolia sitemap, we do not want to index them.

2021-09-09 13:06 UTC, iAdramelk commented on utils/paths.ts
> +    path: resolve("public", "algoliasearchmap.xml"),
Please discuss with Cole how to name them. His name has `_` yous don't. Its not important how exactly to name them, but we want it to be consistent.

2021-09-09 14:54 UTC, klizhentas approved these changes

2021-09-10 07:22 UTC, iAdramelk approved these changes

2021-09-10 07:22 UTC, iAdramelk commented on utils/paths.ts
> +    pages: [...docPages],
Nit: 

```suggestion
    pages: docPages,
```

2021-09-10 08:09 UTC, merged