Fix #454: Add terms pages
gravitational/next pull request #471
Opened 2021-09-30 16:21 UTC by iAdramelk

Added default text layout for terms pages and migrated pages from the old engine to the new one. There are couple minor updates to the base components that I decided to include here too, because they are reeeally minor.

Page urls on staging:

- /tos/
- /privacy/
- /previous-terms/tos-11-09-2020
- /previous-terms/privacy-05-05-2021

2021-09-30 16:25 UTC, iAdramelk commented on layouts/ContentPage/ContentPage.tsx
> +const components = {
We starting reusing this style of components a lot. We need to move them to separate place and add default styling for all markdown elements here.

2021-09-30 16:25 UTC, iAdramelk commented on utils/mdx-config-site.ts
> +          content: "layouts/ContentPage",
I plan to move all layout components to separate folder, but left `SitePage` for now there it is, to prevent merge conflicts.

2021-09-30 16:25 UTC, iAdramelk commented on utils/paths.ts
> +  new RegExp(`^${pagesRoot}/previous-terms/.*$`),
We need a better way to handle removing pages from sitemap that this. Old site had ability to set `noindex: true` field in the frontmatter. Maybe implement it too?

2021-09-30 22:17 UTC, C-STYR requested changes

2021-09-30 22:17 UTC, C-STYR commented on pages/tos.mdx
> +```
I think you should specify a neutrally-highlighted language; this code block and the one at the bottom have some random highlights; 
UPDATE: this applies to multiple .mdx files in this PR

2021-09-30 22:17 UTC, C-STYR commented on pages/privacy.mdx
> +| Type of Cookies                      | Description
Table either needs styling or needs styling correction; it lacks similarity to the original.
UPDATE: this applies to multiple .mdx files in this PR

2021-09-30 22:17 UTC, C-STYR commented on layouts/ContentPage/ContentPage.tsx
> +const components = {
I agree! Let's chat about it on Monday

2021-10-01 02:37 UTC, iAdramelk commented on pages/privacy.mdx
> +| Type of Cookies                      | Description
Can you elaborate? Table now uses the same styles as the one in docs https://goteleport.com/docs/adopters/ . They are different from the old ones but I don't think that its a good idea to have few different types of table styles across the site in different places and we spent some time redesigning and updating tables for the docs. I think our goal here is not 1-on-1 visual parity with the original, but also updating styles in the places where we already have updated components.

2021-10-01 16:36 UTC, C-STYR commented on pages/privacy.mdx
> +| Type of Cookies                      | Description
We will have at least two styles then: the original ones here in /tos and /privacy are the same as those in the How It Works section (see the last three pages where the compliance tables are) and potentially elsewhere.  I have already built a Styled Component to replicate those styles for the HIW page transfer. @alexwolfe perhaps you should make a call here on which table style you want to use going forward, or multiple styles? I personally don't mind either way.

2021-10-01 16:37 UTC, C-STYR commented on pages/privacy.mdx
> +| Type of Cookies                      | Description
Example of Compliance Table: https://goteleport.com/teleport/how-it-works/soc2-ssh-kubernetes/

2021-10-04 19:00 UTC, alexwolfe commented
Hey Team, lets use the original table style for these tables (purple header). We will be updating the Docs table eventually as well (it will not be the same as the marketing site) to give it a slightly better visual design. Thanks, let me know if you have any questions!

2021-10-04 19:48 UTC, C-STYR approved these changes

2021-10-04 19:49 UTC, C-STYR commented
Approved pending table styling re Alex's comments...

2021-10-05 14:13 UTC, iAdramelk commented on components/SectionHeader/SectionHeader.tsx
> +  children?: React.ReactNode;
Because I didn't know about `PropsWithChildren`. :) Thanks for the tip, will try it.

2021-10-05 17:51 UTC, iAdramelk commented
@C-STYR Will merge for now to unblock other PRs and then update tables separately.

2021-10-05 17:51 UTC, merged