Create component for successful download page
gravitational/next pull request #564
Opened 2021-11-04 20:15 UTC by sandylcruz

2021-11-10 11:08 UTC, C-STYR commented on components/DownloadSuccess/DownloadSuccess.tsx
> +const BackgroundContainer = styled(Flex)(
In general, for pages like this, let's shoot for all content appearing within the screen on a 13" laptop; I'd probably start with changing the value of `justifyContent` and using props for spacing

2021-11-10 11:55 UTC, C-STYR requested changes
In general, really well done.  Here are a few pointers:
- As you'll note in the comments below, you need to make more use of the `theme.ts` style guide.  For example, all space values under 80px should be uniform factors of 8 as listed in `theme.space` and all colors should use their variable names in `theme.colors`. 
- Shorthand prop names save time and space.
- Make sure you don't build components from scratch that already exist elsewhere, and also try to make use of Next's inbuilt functionality (which is highly optimized) where possible

2021-11-10 11:55 UTC, C-STYR commented on components/DownloadSuccess/DownloadSuccess.tsx
> +    pr: [2, 4],
How can these 2 props be reduced to a single prop?

2021-11-10 11:55 UTC, C-STYR commented on components/DownloadSuccess/DownloadSuccess.tsx
> +    height: "100%",
what effect does the `height` prop have here?

2021-11-10 11:55 UTC, C-STYR commented on components/DownloadSuccess/DownloadSuccess.tsx
> +const PamImage = styled("img")(
We don't use the `img` element; Next supplies us with one and we also have our own `Image` component.  Have a look at other pages to see how we use them.

2021-11-10 11:55 UTC, C-STYR commented on components/DownloadSuccess/DownloadSuccess.tsx
> +  media("sm", {
instead of media queries, explore how to use the Next Image component's various properties.

2021-11-10 11:55 UTC, C-STYR commented on components/DownloadSuccess/DownloadSuccess.tsx
> +  color: "#37474f",
Please reference the style guide (`theme.ts`) for this value

2021-11-10 11:55 UTC, C-STYR commented on components/DownloadSuccess/DownloadSuccess.tsx
> +      paddingTop: ["35px", "43px"],
What's the shorthand for paddingTop? 
Please reference the style guide for spacing values under 80px - this helps create uniformity

2021-11-10 11:55 UTC, C-STYR commented on components/DownloadSuccess/DownloadSuccess.tsx
> +const StyledIcon = styled("img")(
See above about `img` element and style guide and also apply that comment to all subsequent uses of pixel values within SC/SS props

2021-11-10 11:55 UTC, C-STYR commented on components/DownloadSuccess/DownloadSuccess.tsx
> +    transition: transition([["color", "interaction"]]),
What are these states actually doing?

2021-11-10 11:55 UTC, C-STYR commented on components/DownloadSuccess/DownloadSuccess.tsx
> +    paddingLeft: 0,
what's shorthand for `margin` and `paddingLeft`?

2021-11-10 11:55 UTC, C-STYR commented on components/DownloadSuccess/DownloadSuccess.tsx
> +    backgroundColor: "#fafbff",
Is there another color in our style guide that is **very** similar?

2021-11-10 11:55 UTC, C-STYR commented on components/DownloadSuccess/DownloadSuccess.tsx
> +    backgroundPosition: "initial",
For code clarity, how would you write this value numerically?

2021-11-10 11:55 UTC, C-STYR commented on components/DownloadSuccess/DownloadSuccess.tsx
> +    borderTopRightRadius: "md",
Can these be combined, potentially with arrays for responsive styling?

2021-11-10 11:55 UTC, C-STYR commented on components/DownloadSuccess/DownloadSuccess.tsx
> +              <TextFlex>
Entirely up to you, but I think everything within `TextFlex` could be refactored to leverage an array function and perhaps a single custom component and a small input data structure. What do you think? Seems like a lot of code repetition.

2021-11-10 11:55 UTC, C-STYR commented on components/DownloadSuccess/DownloadSuccess.tsx
> +          <Box
Regardless of its appearance in the design package, we should probably also include `Security Policy` amongst these links, a la `/newsletter/`

2021-11-10 11:55 UTC, C-STYR commented on components/DownloadSuccess/DownloadSuccess.tsx
> + * @returns a standalone, full-page component
Since this component is standalone, we probably don't need to import it by itself into a `.mdx` file. Instead, it could all be potentially one `.tsx` file within `pages/success`.  But given its emerging ubiquity as a design pattern, we may want to in future look at modularizing it as a wrapper to accept R/L side children. Think `Registration` but more generic. Let's discuss.

2021-11-10 11:55 UTC, C-STYR commented on pages/success/index.mdx
> +import { DownloadSuccess } from "components";
See top-level comment about this file, which is probably superfluous.

2021-11-10 11:59 UTC, C-STYR commented on components/DownloadSuccess/DownloadSuccess.tsx
> +    color: "grey",
did you mean "gray"?

2021-11-10 15:52 UTC, sandylcruz commented on components/DownloadSuccess/DownloadSuccess.tsx
> +    height: "100%",
No effect anymore, removing

2021-11-10 16:58 UTC, sandylcruz commented on components/DownloadSuccess/DownloadSuccess.tsx
> +  color: "#37474f",
In the future, should I use the closest color / number in `theme.ts` instead of making the component pixel perfect to the design?

2021-11-10 17:55 UTC, sandylcruz commented on components/DownloadSuccess/DownloadSuccess.tsx
> +    pr: [2, 4],
Got it, `px`

2021-11-10 19:04 UTC, sandylcruz commented on components/DownloadSuccess/DownloadSuccess.tsx
> +const BackgroundContainer = styled(Flex)(
Got it, removed `justifyContent` and used `px` instead

2021-11-10 19:07 UTC, sandylcruz commented on components/DownloadSuccess/DownloadSuccess.tsx
> +              <TextFlex>
Yes there's a lot of repetition. I've changed the top block of links into an array of objects that's iterated over in order to reduce the space.

2021-11-10 19:08 UTC, sandylcruz commented on components/DownloadSuccess/DownloadSuccess.tsx
> + * @returns a standalone, full-page component
I can see it both ways so it would make more sense for the component to be reusable then. Should this be refactored into a reusable component now or wait until later?

2021-11-10 19:09 UTC, sandylcruz commented on components/DownloadSuccess/DownloadSuccess.tsx
> +    color: "grey",
yes "gray", though this property doesn't seem to be changing the links' colors. Updated to add `color` to `Link` instead.

2021-11-10 19:09 UTC, sandylcruz commented on components/DownloadSuccess/DownloadSuccess.tsx
> +const StyledIcon = styled("img")(
Got it, figured out how to use `NextImage` and make it work.

2021-11-10 19:10 UTC, sandylcruz commented on components/DownloadSuccess/DownloadSuccess.tsx
> +    transition: transition([["color", "interaction"]]),
Nothing - removed. I found these values on `Registration`. Should these be removed from there as well?

2021-11-10 19:10 UTC, sandylcruz commented on components/DownloadSuccess/DownloadSuccess.tsx
> +    paddingLeft: 0,
`m` and `pl`

2021-11-10 19:10 UTC, sandylcruz commented on components/DownloadSuccess/DownloadSuccess.tsx
> +    backgroundPosition: "initial",
`0`

2021-11-10 19:34 UTC, sandylcruz commented on components/DownloadSuccess/DownloadSuccess.tsx
> +const BackgroundContainer = styled(Flex)(
Should all `justifyContent` and `alignItems` instances be removed and padding / margin be used instead?

2021-11-11 16:33 UTC, C-STYR requested changes

2021-11-11 16:33 UTC, C-STYR commented on components/DownloadSuccess/DownloadSuccess.tsx
> + * @returns a standalone, full-page component
Later--but it doesn't need to be a component at all currently; just put this logic into a function in `pages/success/index.tsx` and return the singular function as the default;

2021-11-11 16:37 UTC, C-STYR commented on components/DownloadSuccess/DownloadSuccess.tsx
> +const BackgroundContainer = styled(Flex)(
Sorry--didn't want you to remove `justifyContent`, just change the value (in this case to `center`). That way you have more control over the spacing between the items.

2021-11-11 16:37 UTC, C-STYR commented on components/DownloadSuccess/DownloadSuccess.tsx
> +  color: "#37474f",
yes, unless there's a really good reason not to

2021-11-11 16:42 UTC, C-STYR commented on components/DownloadSuccess/DownloadSuccess.tsx
> +    transition: transition([["color", "interaction"]]),
TBD, but probably. When I built `Registration` I didn't really know what I was doing with these props and probably copied them from another component.  Def a bit of Cargo Cult programming in my early work with SC/SS (google that if you're not familiar)

2021-11-11 16:43 UTC, C-STYR commented on components/DownloadSuccess/DownloadSuccess.tsx
> +    backgroundPosition: "initial",
or `0% 0%`

2021-11-11 16:49 UTC, sandylcruz commented on components/DownloadSuccess/DownloadSuccess.tsx
> +            <Box justifyContent="center" margin={["45px 18px", "64px 40px"]}>
yes, done

2021-11-11 17:22 UTC, sandylcruz commented on components/DownloadSuccess/DownloadSuccess.tsx
> +            <Box justifyContent="center" margin={["45px 18px", "64px 40px"]}>
yes, done

2021-11-11 17:22 UTC, sandylcruz commented on components/DownloadSuccess/DownloadSuccess.tsx
> +    fontWeight: "regular",
nope, removed

2021-11-11 17:36 UTC, C-STYR requested changes

2021-11-11 17:36 UTC, C-STYR commented on components/Icon/Icon.tsx
> +  name: IconName | string;
Def cannot do this: it's typed for a reason!

2021-11-12 11:33 UTC, C-STYR approved these changes

2021-11-12 11:39 UTC, C-STYR commented
Approved, but just 2 more things to update before you merge: 
- remove `alt` prop from your LI types if you aren't going to use it (you don't need it for an icon anyway)
- icons should have their color changed by passing in `color`, not `fill`.  See `Tile.tsx`, `GridDisplay.tsx`, or search for `currentColor` to see how this operates.  If your new svgs do not change color when the `color` prop is changed, they may need to be modified again directly

2021-11-16 00:43 UTC, merged