Created BenefitCard for new benefits page
gravitational/next pull request #602
Opened 2021-11-18 15:43 UTC by C-STYR

- creates BenefitCard
- updates GridDisplay and associated components
- adds associated imagery

2021-11-18 16:19 UTC, deliaconstantino commented on pages/about/benefits/index.mdx
> +    - [Guardian Guardian Long-Term Disability (age 65)]()
Are there links missing here (lines 54 & 57)?

2021-11-18 16:21 UTC, deliaconstantino approved these changes

2021-11-19 13:40 UTC, Alqanar requested changes
Thank you for the PR!
I left few comments.

2021-11-19 13:40 UTC, Alqanar commented on components/GridDisplay/BenefitCard.tsx
> +        </Flex>
```suggestion
        <Flex
          flexDirection="column"
          flexGrow={1}
          p={4}
          borderRadius="0 0 8px 8px"
          css={css({ "p, li": { fontSize: "text-md", lineHeight: "md" } })}
        >
          {children}
        </Flex>
```

2021-11-19 13:40 UTC, Alqanar commented on components/GridDisplay/BenefitCard.tsx
> +        </Flex>
We can get rid of inner wrapper with no visual changes

2021-11-19 13:40 UTC, Alqanar commented on components/GridDisplay/BenefitCard.tsx
> +        fontSize="text-xl"
Please add a tag here `as="h2"`. 
In my opinion, since we have a header, let it have an appropriate tag

2021-11-19 13:42 UTC, C-STYR commented on pages/about/benefits/index.mdx
> +    - [Guardian Guardian Long-Term Disability (age 65)]()
Yes, they have not been provided by Design yet.

2021-11-19 14:20 UTC, C-STYR commented on components/GridDisplay/BenefitCard.tsx
> +        </Flex>
Good, very efficient, thanks.

2021-11-19 14:21 UTC, C-STYR commented on components/GridDisplay/BenefitCard.tsx
> +);
Fixed.

2021-11-19 14:24 UTC, C-STYR commented on components/GridDisplay/BenefitCard.tsx
> +        mb={4}
@Alqanar the `min-height` property was actually for vertical alignment of the top of the card.  If removed, we get this: 

![Screen Shot 2021-11-19 at 3 14 25 PM](https://user-images.githubusercontent.com/73362670/142636960-30e1ad0c-a7ff-4baa-a3ac-f970679d3596.png)

...when there is no `title` passed in, as the `title` is part of the card though properly outside its visible border/box-shadow area.  `min-height` was the method I chose to retain that negative space throughout responsive views, as my experimentations with `mt` were unsatisfactory if `title` were present.

2021-11-19 14:24 UTC, C-STYR commented on components/GridDisplay/BenefitCard.tsx
> +        fontSize="text-xl"
Agreed.

2021-11-19 14:27 UTC, Alqanar commented on components/GridDisplay/BenefitCard.tsx
> +        mb={4}
That's weird. Let me see.

2021-11-19 14:43 UTC, Alqanar commented on components/GridDisplay/BenefitCard.tsx
> +        mb={4}
I propose this option
```      
      {!!title && (
        <Box
          as="h2"
          fontSize="text-xl"
          lineHeight="lg"
          color="dark-purple"
          fontWeight="black"
          mt={[3, 0]}
        >
          {title}
        </Box>
      )}

      <StyledWrapper
        backgroundImage={backgroundImage}
        pt={src ? 0 : ["90px", "112px"]}
        mt={title ? [3, 4] : [5, 8]}
      >
        {/* top half */}
```
would look something like this

<img width="1361" alt="Screenshot 2021-11-19 at 17 40 10" src="https://user-images.githubusercontent.com/41822696/142641151-8d706c40-0d57-4071-b211-6543907e5bb7.png">
<img width="366" alt="Screenshot 2021-11-19 at 17 39 53" src="https://user-images.githubusercontent.com/41822696/142641170-0ff952d8-4b1d-4b42-b3e3-36fdc6feb51d.png">

2021-11-19 14:47 UTC, Alqanar commented on components/GridDisplay/BenefitCard.tsx
> +        mb={4}
In this option we put the title under the condition. `mt` moved to the next tag (`StyledWrapper`). And If we don't have the title we will increase margin.

2021-11-19 14:50 UTC, C-STYR commented on components/GridDisplay/BenefitCard.tsx
> +        mb={4}
This works but creates greater complexity.  Why is `min-height` objectionable?  Is there a technical reason?

2021-11-19 14:53 UTC, Alqanar commented on components/GridDisplay/BenefitCard.tsx
> +        mb={4}
The problem is that you are using the `min-height` property for margin, which means you are not using it as intended.

2021-11-19 15:44 UTC, Alqanar approved these changes

2021-11-22 13:10 UTC, merged