Migrate /ssh-jump-server page
gravitational/next pull request #622
Opened 2021-11-23 16:57 UTC by sandylcruz

2021-11-30 11:48 UTC, C-STYR requested changes
See comments.

2021-11-30 11:48 UTC, C-STYR commented on pages/ssh-jump-server/index.mdx
> +    <h2>Additional Benefits of Teleport</h2>
```suggestion
    ## Additional Benefits of Teleport
```

2021-11-30 11:48 UTC, C-STYR commented on pages/ssh-jump-server/index.mdx
> +    <Button as={Link} href="/contact-us" shape="lg">
let's get in the habit of always adding a trailing slash.  Also, we need more margin under the button on mobile, I suggest adding `mb={[3, 0]}` to the button itself.

2021-11-30 11:48 UTC, C-STYR commented on pages/ssh-jump-server/index.mdx
> +<Box py={5}>
Why are we wrapping `GridDisplay` in a `Box`?

2021-11-30 18:24 UTC, sandylcruz commented on pages/ssh-jump-server/index.mdx
> +    <Box display="flex" maxWidth="1240px">
`Flex` was behaving strangely when I used it instead of `Box`. Will play around with `Flex` to convert the `Box`es

2021-11-30 18:25 UTC, sandylcruz commented on pages/ssh-jump-server/index.mdx
> +<Box py={5}>
No reason, just couldn't get padding under `GridDisplay`. Fixed it by adding `pt` on the lower element

2021-11-30 18:26 UTC, sandylcruz commented on components/ListCard/ListCard.tsx
> +const StyledTextWithTitle = styled("div")(
makes sense, updating

2021-11-30 18:26 UTC, sandylcruz commented on pages/ssh-jump-server/index.mdx
> +<SectionHeader
Changed something quickly last night, and didn't double check if it impacted `SectionHeader`. Updating with correct props now

2021-11-30 18:27 UTC, sandylcruz commented on components/TOC/TOCLayout.stories.tsx
>  export const Default = generateStoryComponent();
Oops, separating into separate pr

2021-11-30 18:28 UTC, sandylcruz commented on pages/ssh-jump-server/index.mdx
> +  <GridDisplay cardStyle="productCard" bg="flatWhite">
I had it as `wavelight`, but the background leaves a demarcation above it

<img width="1220" alt="Screen Shot 2021-11-30 at 10 26 51 AM" src="https://user-images.githubusercontent.com/60662264/144106146-165b2278-2d1d-49ff-9157-fb533b94f14b.png">

2021-11-30 18:28 UTC, sandylcruz commented on pages/ssh-jump-server/index.mdx
> +<Centrator
Got it, makes more sense to add the props to `Flex` instead of multiple `Centrator`s.

2021-11-30 23:06 UTC, sandylcruz commented
@C-STYR Updated per your comments. Only change I didn't make was getting rid of all `maxWidth` instances. In the original, the "Why Use Teleport" and "Pricing that scales with you" sections  have `maxWidth` set.

2021-12-01 11:50 UTC, C-STYR commented
@sandylcruz looks good now- my comments about `maxWidth` only pertained to those instances in which it was set on an element wrapped in `Centrator` with the same value as that of the wrapper.  The ones you left are fine - with the one exception of line 149: the value "384px" is wider than screen size on iPhoneX, which is the smallest device size we are targeting.  Let's change to "100%".

2021-12-01 11:50 UTC, C-STYR approved these changes

2021-12-01 16:41 UTC, merged