Refactor AnnouncementBar
gravitational/next pull request #704
Opened 2021-12-22 15:59 UTC by iAdramelk

`AnnouncementBar` is using `svgr` components for logos right now, but we don't really need them as react components because we do not modify them with css in any way. So I replaces them with static images.

It reduced a size of the pages that used this component a lot. 

E. g. `/what-is-zero-trust/` before refactor – `872kb`, after – `255kb`.

2021-12-22 16:01 UTC, iAdramelk commented on pages/index.mdx
> -    title
`title` prop was not actually used anywhere in the component.

2021-12-22 16:01 UTC, iAdramelk commented on pages/use-cases/aws/index.mdx
> -    backgroundColor="lightest-gray"
`backgroundColor` and other css props does not affect components in any way right now.

2021-12-23 10:00 UTC, Alqanar approved these changes

2021-12-23 16:08 UTC, C-STYR requested changes
Just so this doesn't accidentally get merged: this refactor is incomplete until presentation is brought in line with the original:
- grayscale ABar is the wrong color and the spacing between logos is incorrect
- color version is not displaying all logos on several pages
- color version logos are in some cases the wrong size

2021-12-28 12:41 UTC, Alqanar approved these changes

2021-12-29 09:49 UTC, C-STYR commented
@iAdramelk I'm sure you've got more important things to work on in your remaining time.  This component still needs additional refactoring - the animation timing function is off and the spacings still need work (see top instance on the homepage in the preview).  I'm going to assign Delia or Sandy to clean this up in January so they can have some experience with animations.  Thanks for your hard work on this, we'll take it from here.

2022-01-03 13:30 UTC, C-STYR approved these changes

2022-01-04 12:21 UTC, merged