add variant for past events
gravitational/next pull request #884
Opened 2022-02-02 22:59 UTC by deliaconstantino

2022-02-03 20:11 UTC, alexwolfe commented
Mind removing Bruce from the top section in this PR as well? Thanks!

2022-02-03 20:14 UTC, deliaconstantino commented
> Mind removing Bruce from the top section in this PR as well? Thanks!

No problem, will do!

2022-02-04 16:03 UTC, alexwolfe commented
Visually it looks good to me

2022-02-04 20:16 UTC, C-STYR requested changes
Overall, good job on the layout.  There are several comments to address, mostly minor.  One bit of advice going forward is to think about doing a thorough cleanup before you submit for code review.  Go line by line and see if there is anything that can be cut out, especially if you cut/pasted from another component.  I believe this one could be slimmed down _considerably_.

2022-02-04 20:16 UTC, C-STYR commented on components/GridDisplay/SecurityCard.tsx
> +import {
do we need all these imports? are the resource types of past speakers likely to change or be different?

2022-02-04 20:16 UTC, C-STYR commented on components/GridDisplay/SecurityCard.tsx
> +          // alignItem="end"
remove comment if not needed

2022-02-04 20:16 UTC, C-STYR commented on components/GridDisplay/SecurityCard.tsx
> +          backgroundColor={cardBC}
what is the effect of this property alongside `backgroundImage`?

2022-02-04 20:16 UTC, C-STYR commented on pages/security-visionaries-2022/index.mdx
> +    width="auto"
what effect does this prop have (here and elsewhere)?

2022-02-04 20:37 UTC, deliaconstantino commented on pages/security-visionaries-2022/index.mdx
> +    width="auto"
currently `width="auto"` is doing two things:
1. maintaining space between cards as the screen shrinks. 
With `width="auto":
<img width="531" alt="Screen Shot 2022-02-04 at 3 34 56 PM" src="https://user-images.githubusercontent.com/70108137/152599443-e4924403-fd59-4e63-91c8-86a3d7893a64.png">


Without `width="auto"`:
<img width="503" alt="Screen Shot 2022-02-04 at 3 31 54 PM" src="https://user-images.githubusercontent.com/70108137/152599355-7c682cd7-b084-46a4-8490-85ff5267460d.png">

It also expands the component to cover the viewport when the screen decreases to render 1 card across:
<img width="590" alt="Screen Shot 2022-02-04 at 3 36 06 PM" src="https://user-images.githubusercontent.com/70108137/152599650-1a883392-c819-4249-bbb5-c295f0be1236.png">

2022-02-04 20:40 UTC, deliaconstantino commented on components/GridDisplay/SecurityCard.tsx
> +  cardBG: string;
Based on my discussion this morning with Alex, it sounds like we are moving away from variants on components of this type. I will remove these options and similar optional props to make this a more specific component.

2022-02-04 20:50 UTC, deliaconstantino commented on components/GridDisplay/SecurityCard.tsx
> +  bhColor?: string;
removed optional props or make required

2022-02-04 20:50 UTC, deliaconstantino commented on components/GridDisplay/SecurityCard.tsx
> +  bhColor?: string;
removed `bhColor` per comments above

2022-02-04 20:51 UTC, deliaconstantino commented on components/GridDisplay/SecurityCard.tsx
> +          backgroundColor={cardBC}
removed `backgroundColor`

2022-02-04 20:51 UTC, deliaconstantino commented on components/GridDisplay/SecurityCard.tsx
> +          // alignItem="end"
removed

2022-02-04 20:59 UTC, deliaconstantino commented on pages/security-visionaries-2022/index.mdx
> +    width="auto"
Update: edited gridDisplay which allows `width-"auto"` to be removed without the issue noted above

2022-02-04 21:08 UTC, deliaconstantino commented on components/GridDisplay/GridDisplay.tsx
> +  securityCard: ["repeat(auto-fill, minmax(280px, 1fr) )"],
Updated `GTC` to specify specific columns amounts at various breakpoints, rather than using "auto-fill":
https://github.com/gravitational/next/blob/aa1b2e09db02f91ec91ce5d5dd51b48019ec1a0b/components/GridDisplay/GridDisplay.tsx#L65-L69

2022-02-04 21:09 UTC, deliaconstantino commented on components/GridDisplay/SecurityCard.tsx
> +import {
remove background options per discussion above

2022-02-05 00:34 UTC, C-STYR approved these changes

2022-02-05 00:35 UTC, merged