Restore Form Submission in `/signup`
gravitational/next pull request #896
Opened 2022-02-07 23:23 UTC by C-STYR

Partially addresses gravitational/web#2719.

The original script [found here](https://github.com/gravitational/web/blob/master/layouts/signup/list.html) contained a `dataLayer` push: 
```
<script>
    window.teleport.renderSignupRequestForm(document.getElementById('app'), {
      apiUrl: 'https://teleport.sh', //https://cloud.gravitational.io
      onSuccess: () => {
        window.dataLayer = window.dataLayer || [];
        window.dataLayer.push({
          'event': 'formSubmit',
          'formType': 'Teleport Pro Signup',
        });
      }
    });
  </script>
```
This PR adds that push to the `/next` version.

2022-02-08 08:03 UTC, iAdramelk requested changes

2022-02-08 08:03 UTC, iAdramelk commented on utils/cloud-signup.ts
> +): Promise<void> {
Do we plan to reuse this form somewhere else? If no, you an just hardcode onSuccess inside without using options.

2022-02-08 18:53 UTC, C-STYR commented on components/CloudSignup/CloudSignup.tsx
> +    };
changed

2022-02-08 18:53 UTC, C-STYR commented on utils/cloud-signup.ts
> +): Promise<void> {
changed

2022-02-09 05:41 UTC, iAdramelk commented on utils/gtm.ts
> +        */
It was documented in the past. Not sure why is it not documented anymore. :(

2022-02-09 05:46 UTC, iAdramelk approved these changes

2022-02-09 05:46 UTC, iAdramelk commented on components/CloudSignup/CloudSignup.tsx
> +          GTMEvent("formSubmit", { formType: "Teleport Pro Signup" }),
You maaay want to add braces around the call just to be safe. It will not break anything right now, but GTMEvent return `Promise` (so you can optionally wait until event is sent and callback is fired), and while returning promise here is working now, who knows how GTM code will change in the future.

```suggestion
          { GTMEvent("formSubmit", { formType: "Teleport Pro Signup" }); },
```

2022-02-09 20:53 UTC, merged