Add 'get started' button to use-cases pages
gravitational/next pull request #903
Opened 2022-02-14 19:42 UTC by deliaconstantino

- Add "Get Started" button to header section of each `/use-cases/...` page
- Update `<SectionHeader />` to optionally accept a `width` for its `link` prop.

**Preview Pages:**

2022-02-16 18:26 UTC, deliaconstantino commented
> Let's modify slightly so that if there is a News Item, as in the case of the AWS page, that it is inline with the button rather than following it; that way we create less white space beneath the image (which can't resize much further...). 

For context, the page currently looks like this:
<img width="1917" alt="Screen Shot 2022-02-16 at 1 15 27 PM" src="https://user-images.githubusercontent.com/70108137/154329575-13bd2fc8-126b-406b-9c05-69bf2b4ed9b9.png">

The component tree looks like the following (with a number of props passed in):
```
<Section>
  <SectionHeader />
  <NewsItem />
  <AnnouncementBar />
</Section>
```

Right now the `<NewsItem />` ("Teleport is available in the -aws marketplace svg-") is rendered independently of the <`SectionHeader />` component. To implement the requested change, it looks like `<NewItem />` will need to be added as a prop to `<SectionHeader />`. 

Wanted to verify that we want to go down this route before adding further complexity to `<SectionHeader />`? Alternately `<SectionHeader />` could likely be simplified in a similar manner to the `<ProductBanner />` component that @alexwolfe and I were pairing on yesterday, with the bulk of the details assembled on the index.mdx page, rather than in components.

2022-02-16 20:40 UTC, deliaconstantino commented
> modify slightly so that if there is a News Item, as in the case of the AWS page, that it is inline with the button rather than following it; that way we create less white space beneath the image (which can't resize much further...)

- create optional `inlineChild` prop for `<SectionHeader />` to pass in a child component. This `inlineChild` component is rendered inline with `<Button />` on full screen and slides below on mobile. Preview [here](https://teleport-docs-next-git-delia-add-get-start-a5f16c-gravitational.vercel.app/use-cases/aws/)

- Modified `<NewsItem />`(the component passed to `inlineChild`):
  - Replaced `<Centrator />` with `<Flex />`. `<Centrator />` uses `px="80px"` on full screen, which was causing layout issues when rendering the `<NewsItem />` as an inline element. `<NewsItem />` is currently only used on this page.

- Verified that all pages using SectionHeader render properly

2022-02-17 23:10 UTC, C-STYR requested changes
This was a difficult PR to review.  The major component `SectionHeader` is becoming more bloated as it is being asked to accommodate additional complexity.  It is probably in need of a major refactor/split. Within those constraints you did well to achieve the goal of adding a button, a seemingly simple task, yet not so easy!  

However this PR needs improvement.  Unnecessary props, props that aren't defined in the parent component, unused and duplicate imports are all present here.  Future PRs should undergo a line-by-line cleanup before submission. 

Additionally, the PR was submitted without in-code comments which would increase developer understanding and reduce code review time.  As an example, the introduced complexity of the function of the `inlineChild` prop and `ButtonSection` component should probably be explained in the code base.

2022-02-18 16:14 UTC, deliaconstantino commented on pages/use-cases/aws/index.mdx
> +    isAWS={true}
removed, thank you

2022-02-18 16:15 UTC, deliaconstantino commented on pages/use-cases/aws/index.mdx
> +import NextImage from "next/image";
removed

2022-02-18 16:17 UTC, deliaconstantino commented on pages/use-cases/finance/index.mdx
> +import Button from "components/Button";
removed thank you

2022-02-18 20:28 UTC, deliaconstantino commented on components/NewsItem/NewsItem.tsx
> +      maxWidth="1200px"
Reworked components to account for these use cases:

Changes are best seen with the vercel preview from [this deployment](https://teleport-docs-next-39c55f48h-gravitational.vercel.app/use-cases/aws/) as you can scroll across screen sizes. Added example usage for all three (current) version of `<NewsItem />`

- refactored `<Centrator />` to accept an optional `px` prop which allows the `<NewsItem />` rendered in `<SectionHeader />` to display without the default 80px of `px` - default `px` remain the same for all other use cases.
- refactored `<NewsItem />` to wrap and center content as screen size changes. The original had a bit of weird behavior at small screen sizes:
<img width="538" alt="Screen Shot 2022-02-18 at 3 16 05 PM" src="https://user-images.githubusercontent.com/70108137/154755293-8148d130-4414-4790-b8bb-ff380739a6aa.png">

- refactored `<SectionHeader />`:
  - renamed `inlineChild` prop to `newsItem` to better describe what it renders
  - moved `newsItem` and `<Button />` rendering back into `<SectionHeader />` component to follow existing pattern - let me know if comments are still needed here.
  - added `minWidth` to `newsItem` in `<SectionHeader />` to override the new wrapping from `<NewsItem />` which caused strange spacing in this use case

2022-02-18 20:31 UTC, deliaconstantino commented on components/NewsItem/NewsItem.tsx
> +      flexDirection="row"
This comment applied to the previous iteration with `<Flex/ >`. It is now back to the original `<Centrator />` composition.

2022-02-18 20:31 UTC, deliaconstantino commented on components/NewsItem/NewsItem.tsx
> +      justifyContent="flex-start"
Same as above.

2022-02-18 23:05 UTC, deliaconstantino commented on components/NewsItem/NewsItem.tsx
> +      maxWidth="1200px"
Edited one final thing: `paddingTop` on the "awsMarketplace" svg link to center it vertically with the text that it follows. Preview `use-cases/aws` page [here](https://teleport-docs-next-git-delia-add-get-start-a5f16c-gravitational.vercel.app/use-cases/aws/)

2022-02-22 18:19 UTC, C-STYR approved these changes

2022-02-22 18:24 UTC, merged