Set node version for repository
gravitational/next pull request #906
Opened 2022-02-14 22:08 UTC by sandylcruz

2022-02-15 20:02 UTC, alexwolfe commented on README.md
> +* Run ``` nvm use ``` before running ```yarn dev```
Seem like you should start with this since it appears to be the easier option and probably preferred by most.

2022-02-16 18:43 UTC, C-STYR requested changes

2022-02-16 18:43 UTC, C-STYR commented on README.md
> +
There seem to be further install steps missing, for example installing and/or specifying a default version of `Node` as well as defining which version of Node this codebase should be run on.

2022-02-17 21:15 UTC, C-STYR approved these changes

2022-02-17 21:16 UTC, merged