new use-cases/privileged-access-management/ page
gravitational/next pull request #932
Opened 2022-02-25 18:07 UTC by deliaconstantino

2022-03-08 18:15 UTC, alexwolfe commented
@deliaconstantino  A few things
- PDF Image still appears to be broken in the preview not sure why
- You need a shadow on the image of the Teleport App
- Add the "Easy to get started" and "Try Teleport today" sections at the bottom of the page.

2022-03-08 19:29 UTC, deliaconstantino commented
> * here

Addressed these comments; here is the preview for them: https://teleport-docs-next-git-delia-build-moderni-c02ee0-gravitational.vercel.app/use-cases/privileged-access-management/

2022-03-09 14:41 UTC, deliaconstantino commented
per conversation with @C-STYR: 
- added an optional prop, `imageMarginLeft` to `ProductBanner` for full sized, right-aligned images that need space between image and text block
- resized gif to target 1488 x 800 pixels at 2x sizing. (final gif size: 1488 x 837 to keep its aspect ratio)

2022-03-09 18:26 UTC, C-STYR requested changes
Nice work.  Just a few bits to clean up, but overall a tidy job.

2022-03-09 18:26 UTC, C-STYR commented on components/ProductBanner/ProductBanner.tsx
> +  imageMarginLeft?: boolean;
I feel like this should have been padding rather than margin, thoughts? Happy to be convinced otherwise.
Also, if (and only if, please experiment) we're going to have this problem on a right-aligned full-size image too, let's make sure we account for that here and now.  Let's change the name of this prop to `addImagePadding` or "Margin", whatever we end up with.

2022-03-09 18:26 UTC, C-STYR commented on pages/use-cases/privileged-access-management/index.mdx
> +import { ModerizePam } from "components/AnnouncementBar/data";
"ModerizePam" is misspelled here too.

2022-03-09 18:26 UTC, C-STYR commented on components/AnnouncementBar/data.ts
> +export const ModerizePam: LogoRow[] = expandConfig([
"ModerizePam" is misspelled. Missing an "n".

2022-03-09 18:26 UTC, C-STYR commented on components/AnnouncementBar/logos.ts
> +export { default as colorHealthTap } from "./logos/color-healthtap.svg";
I have not checked these logos for proper size, let's do that in our meeting today.

2022-03-09 19:34 UTC, deliaconstantino commented on components/ProductBanner/ProductBanner.tsx
> +  imageMarginLeft?: boolean;
I tried padding first; however it does not work in this use case. Margin does successfully apply the needed space at all viewports.

Updated to `addImageMargin` which optionally adds `mx` at full screen sizes for right or left images

2022-03-09 19:38 UTC, deliaconstantino commented on pages/use-cases/privileged-access-management/index.mdx
> +import { ModerizePam } from "components/AnnouncementBar/data";
Thanks updated the spelling for all of these

2022-03-09 19:38 UTC, deliaconstantino commented on components/AnnouncementBar/data.ts
> +export const ModerizePam: LogoRow[] = expandConfig([
updated

2022-03-09 19:39 UTC, C-STYR approved these changes

2022-03-09 19:58 UTC, deliaconstantino commented on components/AnnouncementBar/logos.ts
> +export { default as colorHealthTap } from "./logos/color-healthtap.svg";
updated size for vmware logo:
<img width="1142" alt="Screen Shot 2022-03-09 at 2 57 52 PM" src="https://user-images.githubusercontent.com/70108137/157523775-4b4a0128-256f-4537-92aa-2ea563d82307.png">

2022-03-09 20:05 UTC, deliaconstantino commented on components/AnnouncementBar/logos.ts
> +export { default as colorHealthTap } from "./logos/color-healthtap.svg";
It still looks like a slightly large gap, but I think that's because of the copyright symbol on left of vmware coupled with the slope of the Moody's "M". Adding these images for reference.
Before:
<img width="1021" alt="Screen Shot 2022-03-09 at 3 01 08 PM" src="https://user-images.githubusercontent.com/70108137/157524689-3b7d5e2e-fb35-44f5-9752-6fba585cef5c.png">

After:
<img width="1176" alt="Screen Shot 2022-03-09 at 3 00 25 PM" src="https://user-images.githubusercontent.com/70108137/157524712-2c3da473-a881-41e3-9b2d-6e5743f479a9.png">

2022-03-09 20:19 UTC, merged