PAM buyers guide
gravitational/next pull request #933
Opened 2022-02-25 22:28 UTC by deliaconstantino

2022-02-28 20:46 UTC, C-STYR requested changes
Nice effort.  Don't hesitate to second-guess developers who have come before you (including me) when modifying their components.

2022-02-28 20:46 UTC, C-STYR commented on components/PDFTeaser/PDFTeaser.tsx
> +            flexShrink={0}
Not sure this should not shrink - it really compresses the left side at tablet widths.
There's a related issue here too: effective x-axis margins are imbalanced below 1200px.  These are explicitly handled in `Centrator`, which is fine, that can be left as is as it only accounts for 16px each side.  The issue is there is a sizable r-side margin because of the layout on the pdf side.  These need to be evened up for 900-1200px.  Line 35 will need to be changed as well as line 64 (there are other ways of handling it too - I'll leave it up to you).
<img width="909" alt="Screen Shot 2022-02-28 at 11 40 07 AM" src="https://user-images.githubusercontent.com/73362670/156055321-048adce6-f231-4177-ae9e-05b9ac7dc93b.png">

2022-02-28 23:07 UTC, deliaconstantino commented on components/PDFTeaser/PDFTeaser.tsx
> +            <ChildrenContainer>{children}</ChildrenContainer>
As I understand it, using `<p>` tags for paragraphs is better for SEO than `<div>`. The current implementation of `<BookBlock/>` renders the paragraph as a `<div>`, but does allow styling like `fontSize` to be applied as shown:
<img width="1438" alt="Screen Shot 2022-02-28 at 5 55 08 PM" src="https://user-images.githubusercontent.com/70108137/156072347-a4c630ad-4650-4395-9764-38463dbb45b4.png">

Creating the `<ChildrenContainer/>` component allowed rendering the paragraph as a `<p>` and also allowed for targeting the `<p>` tag styling with `"& p"` to render at a larger `fontSize` than the default of "16px" that typically applies to `<p>` tags in mdx files:
<img width="1439" alt="Screen Shot 2022-02-28 at 6 03 04 PM" src="https://user-images.githubusercontent.com/70108137/156073227-7d147e65-7c8e-4697-b394-d7e2cc400075.png">

2022-02-28 23:12 UTC, deliaconstantino commented on components/PDFTeaser/PDFTeaser.tsx
> +      <Flex borderBottom="1px solid" borderColor="lightest-gray">
Yes, added to `Section` and removed the `flex` capability as it doesn't seem to do anything here.

2022-02-28 23:21 UTC, deliaconstantino commented on components/PDFTeaser/PDFTeaser.tsx
> +            <ChildrenContainer>{children}</ChildrenContainer>
This could also be accomplished with inline styling like this: 
```
<Box
css={css({
  pt: [2, 4, 6],
  pb: 2,
  "& p": {
    fontSize: ["text-lg", "text-xl"],
    lineHeight: ["md", "lg"],
    color: "dark-gray",
  },
})}
>
{children}
</Box>
```
Personally, I feel that having the separation is more readable. Thoughts?

2022-02-28 23:27 UTC, deliaconstantino commented on components/PDFTeaser/PDFTeaser.tsx
> +              backgroundSize="496px 113px"
updated to `backgroundSize="cover"`

2022-03-01 02:33 UTC, deliaconstantino commented on components/PDFTeaser/PDFTeaser.tsx
> +            flexShrink={0}
Did some experimenting with this. `flexShrink={0}` helps the main PDF image match the `shadowBg` which is assigned an exact size underneath it. `shadowBg` could probably be edited to shrink along with the image. However the image is a bit more user-friendly imo when it stays at full size. I implemented a different fix by adding `justifyContent="space-between"` to the parent `<Centrator/>`. I think this fixes margin issues without shrinking the image. It also more closely matches the original:

https://user-images.githubusercontent.com/70108137/156093404-42d4353e-ab07-493b-af11-a9df39940231.mp4

2022-03-01 17:32 UTC, C-STYR commented on components/PDFTeaser/PDFTeaser.tsx
> +            <ChildrenContainer>{children}</ChildrenContainer>
Good answer. I prefer the inline version (because I don't have to scroll to alter it - it's all right there visually, and it doesn't require the creation of an additional component), but it's really not a big deal one way or the other.  Totally your call.

2022-03-01 17:38 UTC, C-STYR commented on components/PDFTeaser/PDFTeaser.tsx
> +              backgroundSize="496px 113px"
`100%` and `contain` would also have worked, too.  I'm not sure why the original value was used in this context.

2022-03-01 17:41 UTC, C-STYR commented on components/PDFTeaser/PDFTeaser.tsx
> +            flexShrink={0}
So that works for now.  I suspect that as you add other content to this page you will notice that these margins are off kilter vs other components you add to the page, e.g. `ProductBanner`, IIRC.  This is approved as is, but you'll probably want to update in the PR for the whole page.

2022-03-01 17:42 UTC, C-STYR approved these changes

2022-03-01 17:42 UTC, C-STYR commented
Approved with comments.  Please don't forget to remove your `example` page before merging the component only.

2022-03-01 17:44 UTC, deliaconstantino commented on components/PDFTeaser/PDFTeaser.tsx
> +            flexShrink={0}
That makes sense. I'll update for the full page version as needed.

2022-03-01 17:58 UTC, deliaconstantino commented on components/PDFTeaser/PDFTeaser.tsx
> +            <ChildrenContainer>{children}</ChildrenContainer>
ahh good point that is simpler. Though it requires that the component be invoked from the `.mdx` page with this syntax in order to avoid nested `<p>` tags and unapplied styling:
<img width="817" alt="Screen Shot 2022-03-01 at 12 53 00 PM" src="https://user-images.githubusercontent.com/70108137/156222438-2fa79237-889c-4643-be16-129638a136af.png">

Planning to keep as is to avoid that possibility.

2022-03-01 18:24 UTC, merged