Update DB page to not include only MySQL and PG
gravitational/next pull request #944
Opened 2022-03-02 21:56 UTC by ardeche07

@benarent can you please give this a quick review?  Made the smallest possible change to get this page not terribly inaccurate.

2022-03-02 22:43 UTC, benarent commented on pages/how-it-works/database-access/index.mdx
> +headerDescription: Teleport provides an identity-aware access proxy with native support for SQL & NoSQL databases such as MySQL, PostgreSQL, MongoDB, CockroachDB any many more. This chapter explains
```suggestion
headerDescription: Teleport provides an identity-aware access proxy with native support for SQL & NoSQL databases such as MySQL, PostgreSQL, MongoDB, CockroachDB any many more. This chapter explains how database access works.
```

2022-03-02 22:43 UTC, benarent approved these changes

2022-03-02 23:27 UTC, C-STYR commented on pages/how-it-works/database-access/index.mdx
> +headerDescription: Teleport provides an identity-aware access proxy with native support for SQL & NoSQL databases such as MySQL, PostgreSQL, MongoDB, CockroachDB any many more. This chapter explains
@benarent @ardeche07  ...CockroachDB _and_ many more.

2022-03-03 17:21 UTC, C-STYR requested changes
Looks good to me once typo is fixed that I noted in above comment.

2022-03-03 18:51 UTC, benarent commented on pages/how-it-works/database-access/index.mdx
> +headerDescription: Teleport provides an identity-aware access proxy with native support for SQL & NoSQL databases such as MySQL, PostgreSQL, MongoDB, CockroachDB any many more. This chapter explains
fixed

2022-03-03 18:51 UTC, benarent commented
@C-STYR PTAL

2022-03-03 19:28 UTC, C-STYR approved these changes

2022-03-03 19:29 UTC, C-STYR commented
@benarent please double check the typo - doesn't look like it was committed

2022-04-01 13:14 UTC, ardeche07 commented on pages/how-it-works/database-access/index.mdx
> +headerDescription: Teleport provides an identity-aware access proxy with native support for SQL & NoSQL databases such as MySQL, PostgreSQL, MongoDB, CockroachDB any many more. This chapter explains
```suggestion
headerDescription: Teleport provides an identity-aware access proxy with native support for SQL & NoSQL databases such as MySQL, PostgreSQL, MongoDB, CockroachDB and many more. This chapter explains how database access works.
```

2022-04-01 13:15 UTC, ardeche07 commented
@C-STYR I committed the change for that type. Good to go.

2022-04-11 14:10 UTC, ardeche07 commented
@C-STYR can this one go too?

2022-04-11 22:56 UTC, C-STYR approved these changes

2022-04-11 23:21 UTC, closed without merging